site_name: FLoX
#site_url: https://flox.dev/
repo_name: nathaniel-hudson/FLoX
repo_url: https://github.com/nathaniel-hudson/FLoX


########################################################################################################################
# NAVIGATION
########################################################################################################################


nav:
  - Home:
      - index.md
      - home/federated_learning.md
      - home/globus_compute.md
      - home/proxystore.md
  - Getting Started:
      - getting_started/index.md
      - getting_started/topo.md
      - Strategies:
          - getting_started/strategies_depr/index.md
          - getting_started/strategies_depr/what.md
          - getting_started/strategies_depr/callbacks.md
          - getting_started/strategies_depr/custom.md
  - FAQ: faq.md
  - Publications: publications/index.md
  - Docs: docs/


########################################################################################################################
########################################################################################################################
########################################################################################################################

copyright:
  Copyright &copy; 2022 - 2024 Globus Labs, University of Chicago.

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/funcx/shared_invite/zt-gfeclqkz-RuKjkZkvj1t~eWvlnZV0KA
      name: Join the funcX Slack!
    - icon: fontawesome/brands/github
      link: https://github.com/nathaniel-hudson/FLoX

extra_css:
  - stylesheets/extra.css
  - stylesheets/mkdocstrings.css
  - stylesheets/youtube.css
  - stylesheets/api.css

theme:
  name: material
  language: en
  icon: #assets/logos/favicon-dark.svg
    logo: material/bird
    favicon: material/bird
    repo: fontawesome/brands/github-alt
  #  favicon: ...
  font:
    text: Open Sans
    code: JetBrains Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black # indigo
      accent: amber


########################################################################################################################
########################################################################################################################
########################################################################################################################


plugins:
  - mermaid2
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/generate_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      custom_templates: docs/_templates
      enable_inventory: true
      handlers:
        python:
          setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
          paths: [ flight ]
          load_external_modules: true
          options:
            docstring_section_style: spacy # list
            docstring_style: google
            group_by_category: true
            inherited_members: yes
            line_length: 60
            members_order: source # alphabetical
            merge_init_into_class: yes
            separate_signature: yes
            show_root_full_path: yes
            show_signature_annotations: yes
            show_source: false
            show_submodules: no
            # summary: true


########################################################################################################################
########################################################################################################################
########################################################################################################################


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

      # Math typesetting
  - pymdownx.arithmatex:
      generic: true

  # Syntax highlighting for code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.mark
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

      # Javascript for math typesetting
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
